### Send payment from account 1 to account 2
POST http://localhost:8080/api/payments
Content-Type: application/json
Accept: application/json

{
  "senderId": 1,
  "receiverId": 2,
  "amount": 100.00
}

###

### Another example: Send payment from account 2 to account 3
POST http://localhost:8080/api/payments
Content-Type: application/json
Accept: application/json

{
  "senderId": 2,
  "receiverId": 3,
  "amount": 50.75
}

###

### Account Id is incorrect
POST http://localhost:8080/api/payments
Content-Type: application/json
Accept: application/json

{
  "senderId": 12313,
  "receiverId": 12341234,
  "amount": 50.00
}

###

### Edge case: Insufficient balance (invalid input)
POST http://localhost:8080/api/payments
Content-Type: application/json
Accept: application/json

{
  "senderId": 1,
  "receiverId": 2,
  "amount": 9999999
}