openapi: 3.0.3
info:
  title: Instant Payment API
  version: "1.0.0"
  description: |
    This API handles money transfers between accounts and returns a transaction record.

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/payments:
    post:
      summary: "Send money from one account to another"
      description: >
        Transfers the specified amount from senderId to receiverId.  
        Returns a `TransactionResponse` with details of the transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: "Payment succeeded"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: "Payment failed (e.g. insufficient balance, invalid input)"

components:
  schemas:
    PaymentRequest:
      type: object
      required:
        - senderId
        - receiverId
        - amount
      properties:
        senderId:
          type: integer
          format: int64
          description: "ID of the account sending funds"
          example: 1
        receiverId:
          type: integer
          format: int64
          description: "ID of the account receiving funds"
          example: 2
        amount:
          type: number
          format: double
          description: "Amount to be transferred"
          example: 100.00

    TransactionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "ID of the transaction record"
          example: 10
        senderAccountId:
          type: integer
          format: int64
          description: "The sender's account ID"
          example: 1
        receiverAccountId:
          type: integer
          format: int64
          description: "The receiver's account ID"
          example: 2
        amount:
          type: number
          format: double
          description: "Amount that was transferred"
          example: 100.00
        timestamp:
          type: string
          format: date-time
          description: "Timestamp of the transaction"
          example: "2025-04-06T12:34:56"
